import Navabr from '@/components/Navabr';
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ProvidersWeather from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ 
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${inter.className} lg:overflow-y-hidden` }>
        <ProvidersWeather>
          <Navabr/>
        <div className="container lg:overflow-y-hidden ">
        
          <div className='bg__image bg-opacity-40'/>
        {children}
        </div>
      </ProvidersWeather>
      </body>
    </html>
  )
}
